blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://relno.ppodds.cc/
    about: Check documentation for usage
  - name: 💬 Discussions
    url: https://github.com/ppodds/relno/discussions
    about: Use discussions if you have an idea for improvement and asking questions
