name: Run Unit Tests

on:
  workflow_call:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Build source
        run: pnpm build
      - name: Run unit tests
        run: pnpm test
      - name: Run linter
        run: pnpm lint
